apiVersion: v1
kind: Service
metadata:
  name: patient-api-service
  namespace: ${APP_NAMESPACE}
  labels:
    app: patient-api
spec:
  type: NodePort
  ports:
  - port: ${APP_PORT}
    targetPort: ${APP_PORT}
    nodePort: ${NODE_PORT}
    protocol: TCP
    name: http
  selector:
    app: patient-api
